flat_teaching.Rmd:
  path: dev/flat_teaching.Rmd
  state: active
  R:
  - R/auto_cs.R
  - R/get_cd.R
  - R/get_ss.R
  - R/reset_cs.R
  tests: []
  vignettes: vignettes/basic-usage.Rmd
  inflate:
    flat_file: dev/flat_teaching.Rmd
    vignette_name: Basic Usage
    open_vignette: true
    check: true
    document: true
    overwrite: ask
