# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Download chromedriver
#' 
#' @param dest_dir The path of chrome browser driver and selenium server
#' 
#' @return NULL
#' @importFrom httr2 "resp_status" "req_error" "req_perform" "req_retry" "req_user_agent" "req_cache" "request" "resp_body_json" "resp_body_string"
#' @importFrom utils "download.file" "unzip" "tail"
#' @export
#' @examples
#' get_cd(dest_dir = "C:/Users/Dell/Desktop/test/test")

get_cd <- function(dest_dir) {
  if (!is.character(dest_dir) || dest_dir == "") {
    stop("Error: 'dest_dir' argument must be a valid non-empty string.")
  }
  # Check if Google Chrome is installed and get its version and platform information
  chrome_info <- browser_check(verbose = FALSE)

  major_ver <- as.integer(chrome_info$Chrome$main_version)
  platform <- chrome_info$Chrome$platform

  check_and_update_chromedriver(dest_dir, major_ver, platform)
  return(invisible(NULL))
}

browser_check <- function(verbose = TRUE) {
  # Helper function to print messages based on the verbose flag
  print_message <- function(message, type = "info") {
    if (!verbose) return()
    if (type == "error") {
      cat(crayon::red("\u25CF"), message, "\n")
    } else if (type == "success") {
      cat(crayon::green("\u25CF"), message, "\n")
    } else {
      cat(message, "\n")
    }
  }
  
  # Check if the operating system is Windows
  if (Sys.info()["sysname"] != "Windows") {
    print_message("This function only supports Windows operating systems.", "error")
    return(NULL)
  }
  
  # Define the list of browsers and their registry keys
  browsers <- get_supported_browsers()
  
  # Get platform information
  platform_info <- get_platform_info()
  
  # Initialize a flag to track if the browser is found
  browser_found <- FALSE
  
  # Initialize a list to store results
  result <- list()
  
  # Iterate over each browser to check its installation status
  for (browser in browsers) {
    # Execute the registry query command
    tryCatch({
      reg_query <- system(paste("reg query", shQuote(browser$reg_key),
                                "/v", browser$version_var), intern = TRUE)
      if (length(reg_query) > 0) {
        # Extract the browser version
        browser_version <- regmatches(reg_query, regexpr("\\d+(\\.\\d+)*", reg_query))
        # Extract the main version number
        main_version <- unlist(strsplit(browser_version, "\\."))[1]
        if (tolower(browser$name) == "chrome") {
          print_message("Chrome browser was installed on this computer.", "success")
          browser_found <- TRUE
          # Add the main version and platform to the results
          result[[browser$name]] <- list("main_version" = main_version, "platform" = platform_info)
          break
        }
      }
    }, error = function(e) {
      # If an error occurs, continue to the next browser
    })
  }
  
  # If Chrome browser is not found
  if (!browser_found) {
    print_message("Chrome browser is not installed on this computer.", "error")
  }
  
  # Return the result list
  return(result)
}
# Helper function to define the supported browsers
get_supported_browsers <- function() {
  list(
    list(name = "Chrome", reg_key = "HKEY_CURRENT_USER\\Software\\Google\\Chrome\\BLBeacon", version_var = "version")
    #list(name = "Microsoft Edge", reg_key = "HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\BLBeacon", version_var = "version")
  )
}
# Helper function to get platform information
get_platform_info <- function() {
  sys_info <- Sys.info()
  os_type <- sys_info["sysname"]
  machine_type <- .Platform$r_arch
  bit <- ifelse(.Machine$sizeof.pointer == 4, "32", "64")

  if (os_type == "Linux") {
    return(paste0("linux-", bit))
  } else if (os_type == "Darwin") {
    return(paste0("mac-", machine_type, "-", bit))
  } else if (os_type == "Windows") {
    return(paste0("win", bit))
  } else {
    return("unknown-platform")
  }
}
# Chromedriver check before download
check_and_update_chromedriver <- function(dest_dir, major_ver, platform) {
  # Path to the chromedriver version directory
  chromedriver_version_dir <- file.path(dest_dir, "chromedriver", as.character(major_ver))
  chromedriver_exe_path <- file.path(chromedriver_version_dir, "chromedriver.exe")

  # Check if the chromedriver version directory exists and is not empty
  if (!dir.exists(chromedriver_version_dir) || length(list.files(chromedriver_version_dir)) == 0) {
    download_url <- check_chromedriver_url(major_ver, platform)
    download_chromedriver(download_url, dest_dir)  # Replace with actual download function and URL
    return()
  }

  # Proceed with version comparison
  if (major_ver > as.numeric(basename(chromedriver_version_dir))) {
    download_url <- check_chromedriver_url(major_ver, platform)
    download_chromedriver(download_url, dest_dir)  # Replace with actual download function and URL
  } else if (major_ver == as.numeric(basename(chromedriver_version_dir))) {
    if (file.exists(chromedriver_exe_path)) {
      #cat(green_dot, "An appropriate version of chromedriver.exe is already present.\n")
      cat(crayon::green("\u25CF"), "An appropriate version of chromedriver.exe is already present.\n")
    } else {
      download_url <- check_chromedriver_url(major_ver, platform)
      download_chromedriver(download_url, dest_dir)  # Replace with actual download function and URL
    }
  } else {
    #cat(red_dot, "Please update your Google Chrome browser to the latest version.\n")
    cat(crayon::red("\u25CF"), "Please update your Google Chrome browser to the latest version.\n")
  }
}
# Check chromedriver url
check_chromedriver_url <- function(major_ver, platform) {
  # Retrieve the download URL for chromedriver
  chromedriver_url <- find_chromedriver_url(major_ver, platform)

  # Check the chromedriver URL
  if (!is.null(chromedriver_url) && nzchar(chromedriver_url)) {
    #cat(green_dot, "Chromedriver download URL successfully retrieved.\n")
    cat(crayon::green("\u25CF"), "Chromedriver download URL successfully retrieved.\n")
    return(chromedriver_url)
  } else {
    #cat(red_dot, "Failed to retrieve Chromedriver download URL.\n")
    cat(crayon::red("\u25CF"), "Failed to retrieve Chromedriver download URL.\n")
    return(NA)
  }
}
# Download chromdriver
download_chromedriver <- function(download_url, dest_dir) {
  # Extract main version number from URL
  main_version <- sub(".*/(\\d+).*", "\\1", download_url)

  # Create new directory for the specific version
  version_dir <- file.path(dest_dir, "chromedriver", main_version)
  if (!dir.exists(version_dir)) {
    dir.create(version_dir, recursive = TRUE)
  }

  # Prepare download path
  download_filename <- paste0("chromedriver-", main_version, ".zip")
  download_path <- file.path(dest_dir, download_filename)

  # Download the file with a progress bar
  tryCatch({
    download.file(download_url, destfile = download_path, mode = "wb", quiet = T)
  }, error = function(e) {
    #cat(red_dot, "Chromedriver download failed. \n")
    cat(crayon::red("\u25CF"), "Chromedriver download failed. \n")
    return()
  })

  # Unzip the downloaded zip file to the version directory
  unzip_status <- try({
    unzip(download_path, exdir = version_dir)
    TRUE
  }, silent = TRUE)

  # Check if unzip was successful
  if (unzip_status != TRUE) {
    #cat("Unzip failed. Please check the zip file.\n")
    cat(crayon::red("\u25CF"), "Unzip failed. Please check the zip file.\n")
    return(NULL)
  }

  # Expected path inside the unzipped directory
  nested_dir_path <- file.path(version_dir, "chromedriver-win64")

  # Move chromedriver.exe to the version directory
  exe_path <- file.path(nested_dir_path, "chromedriver.exe")
  final_exe_path <- file.path(version_dir, "chromedriver.exe")
  if (file.exists(exe_path)) {
    file.rename(exe_path, final_exe_path)
    #cat(green_dot, "chromedriver.exe has been successfully moved to ", final_exe_path, ".\n")
  } else {
    #cat("chromedriver.exe not found in the expected directory ", nested_dir_path, ".\n")
    cat(crayon::red("\u25CF"), "chromedriver.exe not found in the expected directory ", nested_dir_path, ".\n")
    return(NULL)
  }

  # Delete the original zip file and the nested directory
  unlink(download_path)
  unlink(nested_dir_path, recursive = TRUE)

  # Print success message
  #cat(green_dot, "Chromedriver.exe has been successfully downloaded to ", version_dir, ".\n")
  cat(crayon::green("\u25CF"), "Chromedriver.exe has been successfully downloaded to ", version_dir, ".\n")
}
# Find chromedriver url
find_chromedriver_url <- function(major_ver, platform) {
  # Convert major_ver from string to number
  major_ver_num <- as.numeric(major_ver)

  # Base URL for older versions
  old_versions_base_url <- "https://chromedriver.storage.googleapis.com"

  # Logic for versions <= 114
  if (major_ver_num <= 114) {
    latest_release_ver <- fetch_latest_release_version(major_ver_num)

    if (!is.null(latest_release_ver) && nchar(latest_release_ver) > 0) {
      base_url <- "https://chromedriver.storage.googleapis.com"
      download_url <- paste0(base_url, "/", latest_release_ver, "/chromedriver_", platform, ".zip")
      return(download_url)
    } else {
      cat("Please update your Google Chrome to version 115 or later.\n")
      return(invisible(NULL))
    }
  }  else {
    # Fetch JSON data
    data <- fetch_json_data()
    if (is.null(data)) {
      cat("Failed to fetch JSON data for versions greater than 114.\n")
      return(invisible(NULL))
    }
    # Logic for versions > 114
    urls <- c()
    available_versions <- sapply(data[2]$versions, function(x) strsplit(x$version, "\\.")[[1]][1])

    if (!major_ver_num %in% available_versions) {
      cat("No ChromeDriver found for major version", major_ver_num, ".\n")
      return(invisible(NULL))
    }

    for (ver_info in data[2]$versions) {
      split_ver <- strsplit(ver_info$version, "\\.")[[1]]
      if (split_ver[1] == major_ver_num) {
        for (dl_info in ver_info$downloads$chromedriver) {
          if (dl_info$platform == platform) {
            urls <- c(urls, dl_info$url)
          }
        }
      }
    }

    if (length(urls) > 0) {
      return(sample(urls, 1))
    } else {
      cat("No suitable download URL found for the specified platform.\n")
      return(invisible(NULL))
    }
  }
}
# Define the user_agent function with additional user agents
user_agent <- function() {
  # List of user agents
  user_agents <- c(
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.3 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/98.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/98.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/98.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/121.0.0.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Edge/121.0.0.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/121.0.0.0"
    # Add more user agents as needed
  )

  # Randomly select a user agent
  selected_user_agent <- sample(user_agents, 1)

  return(selected_user_agent)
}
# Get version>114 JSON
fetch_json_data <- function() {
  url <- "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"

  # 定义错误检测函数
  is_error_response <- function(resp) {
    resp_status(resp) >= 400
  }

  # 定义错误消息体函数
  error_message_body <- function(resp) {
    paste("Error occurred with status code:", resp_status(resp))
  }

  # 准备带有缓存、用户代理、错误处理和重试逻辑的请求
  resp <- request(url) |>
    req_cache(tempdir(), debug = TRUE) |>
    req_user_agent(user_agent()) |>
    req_retry(max_tries = 3, is_transient = \(resp) resp_status(resp) %in% c(429, 500, 503), backoff = ~10) |>
    req_error(is_error = is_error_response, body = error_message_body) |>
    req_perform()

  json_data <- resp_body_json(resp)

  if (is.null(json_data) || !("versions" %in% names(json_data))) {
    cat("Request succeeded, but the returned JSON data does not meet expectations.\n")
    return(NULL)
  }
  return(json_data)
}
# Get version<=114 version
fetch_latest_release_version <- function(major_ver) {
  base_url <- "https://chromedriver.storage.googleapis.com"
  release_url <- paste0(base_url, "/LATEST_RELEASE_", major_ver)

  # 定义错误检测函数
  is_error_response <- function(resp) {
    resp_status(resp) >= 400
  }

  # 定义错误消息体函数
  error_message_body <- function(resp) {
    paste("Error occurred with status code:", resp_status(resp))
  }

  # 准备带有缓存、用户代理、错误处理和重试逻辑的请求
  resp <- request(release_url) |>
    req_cache(tempdir(), debug = TRUE) |>
    req_user_agent(user_agent()) |>
    req_retry(max_tries = 3, is_transient = \(resp) resp_status(resp) %in% c(429, 500, 503), backoff = ~10) |>
    req_error(is_error = is_error_response, body = error_message_body) |>
    req_perform()

  # 检查响应状态并解析响应体
  if (is.null(resp) || resp_status(resp) != 200) {
    cat("Request failed or returned invalid status.\n")
    return(NULL)
  }

  latest_release_ver <- resp_body_string(resp)

  if (is.null(latest_release_ver)) {
    cat("Request succeeded, but no valid version string was returned.\n")
    return(NULL)
  }

  return(latest_release_ver)
}

