# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param dest_dir The path of chrome browser dirver and selenium server
#' 
#' @return NULL
#' 
#' @export
#' @examples
#' get_ss(dest_dir = "C:/Users/Dell/Desktop/test/test")

get_ss <- function(dest_dir) {
  if (!is.character(dest_dir) || dest_dir == "") {
    stop("Error: 'dest_dir' argument must be a valid non-empty string.")
  }
  check_and_download_selenium(dest_dir)
  return(invisible(NULL))
}

check_and_download_selenium <- function(dest_dir) {
  # Path to the selenium directory
  selenium_dir <- file.path(dest_dir, "selenium")

  # Check if the selenium directory exists
  if (!dir.exists(selenium_dir)) {
    download_url <- check_selenium_url(dest_dir)
    download_selenium(download_url, dest_dir)  # Replace with actual download function and URL
    return()
  }

  # Find the latest version directory
  version_dirs <- list.dirs(selenium_dir, full.names = TRUE, recursive = FALSE)
  if (length(version_dirs) == 0) {
    download_url <- check_selenium_url(dest_dir)
    download_selenium(download_url, dest_dir)  # Replace with actual download function and URL
    return()
  }

  latest_version_dir <- version_dirs[which.max(as.numeric(gsub(".*selenium/(\\d+\\.\\d+).*", "\\1", version_dirs)))]

  # Find any .jar files in the latest version directory
  jar_files <- list.files(latest_version_dir, pattern = "\\.jar$", full.names = TRUE)

  # Check if any .jar file exists in the latest version directory
  if (length(jar_files) > 0) {
    #cat(green_dot, "You have already downloaded the .jar file in ", latest_version_dir, ".\n")
    cat(crayon::green("\u25CF"), "You have already downloaded the .jar file in ", latest_version_dir, ".\n")
  } else {
    download_url <- check_selenium_url(dest_dir)
    download_selenium(download_url, dest_dir)  # Replace with actual download function and URL
  }
}

check_selenium_url <- function(dest_dir) {
  # Retrieve the download URL for selenium
  selenium_url <- find_selenium_url(dest_dir)

  # Check the selenium URL
  if (!is.null(selenium_url) && nzchar(selenium_url)) {
    #cat(green_dot, "Selenium download URL successfully retrieved.\n")
    cat(crayon::green("\u25CF"), "Selenium download URL successfully retrieved.\n")
    return(selenium_url)
  } else {
    #cat(red_dot, "Failed to retrieve Selenium download URL.\n")
    cat(crayon::red("\u25CF"), "Failed to retrieve Selenium download URL.\n")
    return(NA)
  }
}

download_selenium <- function(selenium_url, dest_dir) {
  # Extract the version number from URL
  version <- sub(".*/(\\d+\\.\\d+)/.*", "\\1", selenium_url)

  # Create new directory for the specific version
  version_dir <- file.path(dest_dir, "selenium", version)
  if (!dir.exists(version_dir)) {
    dir.create(version_dir, recursive = TRUE)
  }

  # Extract the file name from URL
  selenium_name <- basename(selenium_url)
  selenium_download_path <- file.path(version_dir, selenium_name)

  # Download the Selenium jar file with a progress bar
  tryCatch({
    download.file(selenium_url, destfile = selenium_download_path, mode = "wb", quiet = T)
    #cat(green_dot, "Selenium has been successfully downloaded to ", version_dir, ".\n")
    cat(crayon::green("\u25CF"), "Selenium has been successfully downloaded to ", version_dir, ".\n")
  }, error = function(e) {
    #cat(red_dot, "Selenium download failed.\n")
    cat(crayon::red("\u25CF"), "Selenium download failed.\n")
    return()
  })
}

find_selenium_url <- function(dest_dir) {
  base_url <- "https://selenium-release.storage.googleapis.com/"

  # 定义错误检测函数
  is_error_response <- function(resp) {
    httr2::resp_status(resp) >= 400
  }

  # 定义错误消息体函数
  error_message_body <- function(resp) {
    paste("Error occurred with status code:", httr2::resp_status(resp))
  }

  # 发送请求，包括缓存、重试和错误处理逻辑
  req <- httr2::request(base_url) |>
    httr2::req_user_agent(user_agent()) |>
    httr2::req_cache(tempdir(), debug = TRUE) |>
    httr2::req_retry(max_tries = 3, is_transient = \(resp) httr2::resp_status(resp) %in% c(429, 500, 503), backoff = ~10) |>
    httr2::req_error(is_error = is_error_response, body = error_message_body) |>
    httr2::req_perform() |>
    httr2::resp_body_string()

  # 解析 HTML，寻找最新版本的 selenium-server-standalone jar 文件
  res <- req |>
    rvest::read_html() |>
    rvest::html_elements(xpath = "//key[contains(text(), 'selenium-server-standalone')]") |>
    rvest::html_text2()

  # 提取最新版本的文件名
  latest_version_jar <- tail(grep(".jar$", res, value = TRUE), 1)
  if (length(latest_version_jar) == 0) {
    stop("No selenium-server-standalone jar file found")
  }

  # 构建下载 URL
  selenium_name <- gsub("^[0-9.]+/", "", latest_version_jar)
  selenium_file <- file.path(dest_dir, selenium_name)
  selenium_url <- paste0(base_url, latest_version_jar)

  return(selenium_url)
}


