# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Reset Selenium WebDriver service
#' 
#' @return NULL
#' 
#' @export
#' @examples
#' auto_cs(dest_dir = "C:/Users/Dell/Desktop/test")
#' reset_cs()
reset_cs <- function () {
  # Check and terminate any existing Selenium server processes
  task_list <- system2("wmic", args = c("process", "where", "name='java.exe'", "get", "ProcessId,CommandLine"), stdout = TRUE)
  task_list <- stringi::stri_encode(task_list, from = "", to = "UTF-8")
  task_list_lines <- unlist(strsplit(task_list, split = "\r\n"))
  task_list_lines <- task_list_lines[grep("selenium-server-standalone", task_list_lines)]
  if (length(task_list_lines) > 0) {
    for (line in task_list_lines) {
      pid <- as.integer(gsub("^.*?([0-9]+).*$", "\\1", line))
      system2("taskkill", args = c("/F", "/PID", pid), stdout = FALSE, stderr = FALSE)
      cat(crayon::green("\u25CF"), sprintf("Selenium server process with PID %d terminated.\n", pid))
    }
  } else {
    cat(crayon::red("\u25CF"), "No Selenium server process found.\n")
  }

  # Check and terminate any existing ChromeDriver processes
  chromedriver_list <- system2("wmic", args = c("process", "where", "name='chromedriver.exe'", "get", "ProcessId,CommandLine"), stdout = TRUE)
  chromedriver_list <- stringi::stri_encode(chromedriver_list, from = "", to = "UTF-8")
  chromedriver_list_lines <- unlist(strsplit(chromedriver_list, split = "\r\n"))
  chromedriver_list_lines <- chromedriver_list_lines[grep("chromedriver.exe", chromedriver_list_lines)]
  if (length(chromedriver_list_lines) > 0) {
    for (line in chromedriver_list_lines) {
      pid <- as.integer(gsub("^.*?([0-9]+).*$", "\\1", line))
      system2("taskkill", args = c("/F", "/PID", pid), stdout = FALSE, stderr = FALSE)
      cat(crayon::green("\u25CF"), sprintf("Chromedriver process with PID %d terminated.\n", pid))
    }
  } else {
    cat(crayon::red("\u25CF"), "No Chromedriver process found.\n")
  }

  # Remove startup .bat file if exists
  startup_path <- file.path(Sys.getenv("APPDATA"), "Microsoft", "Windows", "Start Menu", "Programs", "Startup")
  startup_path <- gsub("\\\\", "/", startup_path)
  bat_file <- list.files(startup_path, pattern = ".bat$", full.names = TRUE)
  if (length(bat_file) > 0) {
    file.remove(bat_file)
    cat(crayon::green("\u25CF"), "Startup .bat file removed.\n")
  } else {
    cat(crayon::red("\u25CF"), "No startup .bat file found.\n")
  }
}
