# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param dest_dir The path of chrome browser dirver and selenium server
#' 
#' @return NULL
#' 
#' @export
#' @examples
#' wdauto(dest_dir = "C:/Users/Dell/Desktop/test/test")

wdauto <- function(dest_dir) {
  
  if (!is.character(dest_dir) || dest_dir == "") {
    stop("Error: 'dest_dir' argument must be a valid non-empty string.")
  }
  
  # Check if Google Chrome is installed and get its version and platform information
  browser_check()
  
  # Check if Java is installed
  java_check()
  
  # Start the selenium server
  start_selenium_server(dest_dir)
  
  return(invisible(NULL))
}

java_check <- function() {
  # Check if the operating system is Windows
  if (Sys.info()["sysname"] != "Windows") {
    cat(crayon::red("\u25CF"), "This function only supports Windows operating systems.\n")
    return(invisible(NULL))
  }
  
  # Check for the path of the 'java' command
  javapath <- Sys.which("java")
  if (identical(javapath, "")) {
    cat(crayon::red("\u25CF"), "Java is not installed. Please install Java.\n")
    return(invisible(NULL))
  }
  
  # Execute 'java -version' and capture both stdout and stderr
  java_version_info <- tryCatch({
    suppressWarnings(system2(javapath, "-version", stdout = TRUE, stderr = TRUE))
  }, error = function(e) {
    #cat(red_dot, "Error occurred while checking Java version.\n")
    cat(crayon::red("\u25CF"), "Error occurred while checking Java version.\n")
    return(invisible(NULL))
  })
  
  # Check for any status attribute that indicates an error
  if (!is.null(attr(java_version_info, "status"))) {
    #cat(red_dot, "Error occurred while checking Java version.\n")
    cat(crayon::red("\u25CF"), "Error occurred while checking Java version.\n")
    return(invisible(NULL))
  }
  
  # If execution reaches here, it means Java is installed
  #cat(green_dot, "Java is installed on this computer.\n")
  cat(crayon::green("\u25CF"), "Java is installed on this computer.\n")
  
  invisible(NULL)
}
start_selenium_server <- function(dest_dir) {
  if (identical(Sys.getenv("R_CMD_CHECK"), "true")) {
    cat("Selenium server start skipped during R CMD CHECK.\n")
    return(invisible(NULL))
  }
  
  # Check and terminate any existing Selenium server processes
  task_list <- system2("wmic", args = c("process", "where",
                                        "name='java.exe'", "get", "ProcessId,CommandLine"),
                       stdout = TRUE)
  task_list <- stringi::stri_encode(task_list, from = "",
                                    to = "UTF-8")
  task_list_lines <- unlist(strsplit(task_list, split = "\r\n"))
  task_list_lines <- task_list_lines[grep("selenium-server-standalone",
                                          task_list_lines)]
  if (length(task_list_lines) > 0) {
    for (line in task_list_lines) {
      pid <- as.integer(gsub("^.*?([0-9]+).*$", "\\1",
                             line))
      system2("taskkill", args = c("/F", "/PID", pid),
              stdout = FALSE, stderr = FALSE)
      # cat(red_dot, sprintf("Old selenium server process with PID %d terminated.\n",
      #                      pid))
      cat(crayon::red("\u25CF"), sprintf("Old selenium server process with PID %d terminated.\n",
                                         pid))
    }
    Sys.sleep(5)
  }
  
  # Set up path for ChromeDriver
  chromedriver_version_dir <- file.path(dest_dir, "chromedriver")
  browser_files <- list.files(chromedriver_version_dir, pattern = "chromedriver\\.exe$", full.names = TRUE, recursive = TRUE)
  if (length(browser_files) > 0) {
    browser_file <- browser_files[1]  # Assuming the first one is the desired version
  } else {
    #cat(red_dot, "Error: Chromedriver.exe not found.\n")
    cat(crayon::red("\u25CF"), "Error: Chromedriver.exe not found.\n")
    return()
  }
  
  # Set up path for the latest version of Selenium server .jar
  selenium_version_dir <- file.path(dest_dir, "selenium")
  if (dir.exists(selenium_version_dir)) {
    selenium_files <- list.files(selenium_version_dir, pattern = "\\.jar$", full.names = TRUE, recursive = TRUE)
    selenium_versions <- lapply(selenium_files, function(x) {
      as.numeric(gsub(".*selenium-server-standalone-(\\d+\\.\\d+).*\\.jar$", "\\1", x))
    })
    latest_index <- which.max(unlist(selenium_versions))
    if (length(selenium_files) > 0 && !is.na(latest_index)) {
      selenium_file <- selenium_files[latest_index]
    } else {
      #cat(red_dot, "Error: Selenium server jar file not found.\n")
      cat(crayon::red("\u25CF"), "Error: Selenium server jar file not found.\n")
      return()
    }
  } else {
    #cat(red_dot, "Error: Selenium directory not found.\n")
    cat(crayon::red("\u25CF"), "Error: Selenium directory not found.\n")
    return()
  }
  
  # 构建并执行启动 Selenium server 的命令
  command <- sprintf("java -Dwebdriver.chrome.driver=\"%s\" -jar \"%s\"", browser_file, selenium_file)
  if (interactive()) {
    system(command, wait = FALSE)
    Sys.sleep(5)  # 为 Selenium Server 提供启动时间

    port <- 4444  # Selenium Server 的默认端口
    success <- tryCatch({
        con <- socketConnection(port = port, open = "r+", timeout = 5)
        close(con)
        TRUE
    }, error = function(e) {
        FALSE
    })

    if (success) {
        cat(crayon::green("\u25CF"), "Selenium server is up and running on port ", port, ".\n")
    } else {
        cat(crayon::red("\u25CF"), "Error: Failed to start Selenium server on port ", port, ".\n")
    }
  }
  
  
  # Create a batch file for startup if it doesn't exist
  startup_path <- file.path(Sys.getenv("APPDATA"), "Microsoft",
                            "Windows", "Start Menu", "Programs", "Startup")
  startup_path <- gsub("\\\\", "/", startup_path)
  bat_file <- file.path(startup_path, "chrome_driver.bat")
  
  if (!file.exists(bat_file)) {
    bat_content <- paste("@echo off", "cd /d %~dp0",
                         "if \"%1\" == \"h\" goto begin", "mshta vbscript:createobject(\"wscript.shell\").run(\"%~nx0 h\",0)(window.close)&&exit",
                         ":begin", command, sep = "\n")
    writeLines(bat_content, con = bat_file)
  }
}
